title: KGE Project - Tourism and Waste Management in Trentino
description: Knowledge Graph Engineering project for tourism and waste management analysis
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
repository: pariamelle/KGE-Project-Tourism-Waste-Management-in-Trentino
